#ifndef _DATABASE_SPELL_H
#define _DATABASE_SPELL_H

#include "Database_Common.h"

static SortedChoiceItemWithHelp HADES_STRING_SPELL_EFFECT[] = {
	{ 0, L"No Effect", L"No effect." },
	{ 1, L"Attack Standard", L"Standard weapons attack.\nDamage = (Attack - Defence) * Random[Strength, Strength + (Level + Strength) / 8]\nHit Rate = 100\nCritical Rate = Spirit / 8\n\nDamage Modifiers\n Caster : Killer Abilities, MP Attack, Healer, Berserk, Trance, Mini, Back Row and Elemental Boost (Weapon)\n Target : Defend, Protect, Sleep, Mini, Back Attack, Back Row, Gamble Defence and Elemental Affinity (Weapon)\n Other : Ipsen's Curse\nHit Rate Modifiers\n Caster : Accuracy+, Confuse, Blind, Trance and Vanish\n Target : Distract, Defend, Vanish, Petrify, Venom, Virus, Blind, Confuse, Stop, Sleep and Freeze\nUse physical evasion.\nKill Frozen targets.\nSpread damage if the target is under Trouble.\nAdd weapon's status with Add Status (use weapon's status accuracy)." },
	{ 2, L"Attack Thief Sword", L"Thief swords and Knight swords attack.\nDamage = (Attack - Defence) * (Random[Strength, Strength + (Level + Strength) / 8] + Spirit / 2)\nHit Rate = 100\nCritical Rate = Spirit / 8\n\nDamage Modifiers\n Caster : Killer Abilities, MP Attack, Healer, Berserk, Trance, Mini, Back Row and Elemental Boost (Weapon)\n Target : Defend, Protect, Sleep, Mini, Back Attack, Back Row, Gamble Defence and Elemental Affinity (Weapon)\n Other : Ipsen's Curse\nHit Rate Modifiers\n Caster : Accuracy+, Confuse, Blind, Trance and Vanish\n Target : Distract, Defend, Vanish, Petrify, Venom, Virus, Blind, Confuse, Stop, Sleep and Freeze\nUse physical evasion.\nKill Frozen targets.\nSpread damage if the target is under Trouble.\nAdd weapon's status with Add Status (use weapon's status accuracy)." },
	{ 3, L"Attack Rackets", L"Rackets attack.\nDamage = (Attack - Defence) * (Random[Strength, Strength + (Level + Strength) / 8] + Speed / 2)\nHit Rate = 100\nCritical Rate = Spirit / 8\n\nDamage Modifiers\n Caster : Killer Abilities, MP Attack, Healer, Berserk, Trance, Mini, Back Row and Elemental Boost (Weapon)\n Target : Defend, Protect, Sleep, Mini, Back Attack, Back Row, Gamble Defence and Elemental Affinity (Weapon)\n Other : Ipsen's Curse\nHit Rate Modifiers\n Caster : Accuracy+, Confuse, Blind, Trance and Vanish\n Target : Distract, Defend, Vanish, Petrify, Venom, Virus, Blind, Confuse, Stop, Sleep and Freeze\nUse physical evasion.\nKill Frozen targets.\nSpread damage if the target is under Trouble.\nAdd weapon's status with Add Status (use weapon's status accuracy)." },
	{ 4, L"Attack Scrolls", L"Magical weapons attack.\nDamage = (Attack - Defence) * (Random[Strength, Strength + (Level + Strength) / 8] + Magic / 2)\nHit Rate = 100\nCritical Rate = Spirit / 8\n\nDamage Modifiers\n Caster : Killer Abilities, MP Attack, Healer, Berserk, Trance, Mini, Back Row and Elemental Boost (Weapon)\n Target : Defend, Protect, Sleep, Mini, Back Attack, Back Row, Gamble Defence and Elemental Affinity (Weapon)\n Other : Ipsen's Curse\nHit Rate Modifiers\n Caster : Accuracy+, Confuse, Blind, Trance and Vanish\n Target : Distract, Defend, Vanish, Petrify, Venom, Virus, Blind, Confuse, Stop, Sleep and Freeze\nUse physical evasion.\nKill Frozen targets.\nSpread damage if the target is under Trouble.\nAdd weapon's status with Add Status (use weapon's status accuracy)." },
	{ 5, L"Attack Forks", L"Forks and Hammers attack.\nDamage = (Attack - Defence) * Random[0, Random[Strength, Strength + (Level + Strength) / 8]]\nHit Rate = 100\nCritical Rate = Spirit / 8\n\nDamage Modifiers\n Caster : Killer Abilities, MP Attack, Healer, Berserk, Trance, Mini, Back Row and Elemental Boost (Weapon)\n Target : Defend, Protect, Sleep, Mini, Back Attack, Back Row, Gamble Defence and Elemental Affinity (Weapon)\n Other : Ipsen's Curse\nHit Rate Modifiers\n Caster : Accuracy+, Confuse, Blind, Trance and Vanish\n Target : Distract, Defend, Vanish, Petrify, Venom, Virus, Blind, Confuse, Stop, Sleep and Freeze\nUse physical evasion.\nKill Frozen targets.\nSpread damage if the target is under Trouble.\nAdd weapon's status with Add Status (use weapon's status accuracy)." },
	{ 6, L"Attack Blood Sword", L"Blood Sword attack. Heal the caster by the damage amount, but reverse the process on Zombie.\nDamage = (Attack - Defence) * Random[Strength, Strength + (Level + Strength) / 8]\nHit Rate = 100\nCritical Rate = Spirit / 8\n\nDamage Modifiers\n Caster : Killer Abilities, MP Attack, Berserk, Trance, Mini and Back Row\n Target : Defend, Protect, Sleep, Mini, Back Attack, Back Row and Gamble Defence\n Other : Ipsen's Curse\nHit Rate Modifiers\n Caster : Accuracy+, Confuse, Blind, Trance and Vanish\n Target : Distract, Defend, Vanish, Petrify (miss), Venom, Virus, Blind, Confuse, Stop, Sleep and Freeze\nUse physical evasion.\nKill Frozen targets.\nSpread damage if the target is under Trouble." },
	{ 7, L"Attack Save The Queen", L"Save The Queen attack.\nDamage = (Attack + Level - Defence) * Random[Strength, Strength + (Level + Strength) / 8]\nHit Rate = 100\nCritical Rate = Spirit / 8\n\nDamage Modifiers\n Caster : Killer Abilities, MP Attack, Healer, Berserk, Trance, Mini, Back Row and Elemental Boost (Weapon)\n Target : Defend, Protect, Sleep, Mini, Back Attack, Back Row, Gamble Defence and Elemental Affinity (Weapon)\n Other : Ipsen's Curse\nHit Rate Modifiers\n Caster : Accuracy+, Confuse, Blind, Trance and Vanish\n Target : Distract, Defend, Vanish, Petrify, Venom, Virus, Blind, Confuse, Stop, Sleep and Freeze\nUse physical evasion.\nKill Frozen targets.\nSpread damage if the target is under Trouble.\nAdd weapon's status with Add Status (use weapon's status accuracy)." },
	{ 8, L"Enemy Attack", L"Physical attack used by enemies that can also add status.\nDamage = (Attack - Defence) * Random[Strength, Strength + (Level + Strength) / 4]\nHit Rate = 100\nStatus Hit Rate = SpellAccuracy\nCritical Rate = Spirit / 8\n\nDamage Modifiers\n Caster : Healer, Berserk, Trance, Mini, Back Row and Elemental Boost\n Target : Defend, Protect, Sleep, Mini, Back Attack, Back Row, Gamble Defence and Elemental Affinity\nHit Rate Modifiers\n Caster : Confuse, Blind, Trance and Vanish\n Target : Distract, Defend, Vanish, Petrify, Venom, Virus, Blind, Confuse, Stop, Sleep and Freeze\nUse physical evasion.\nKill Frozen targets.\nSpread damage if the target is under Trouble." },
	{ 9, L"Magic Attack", L"Basic magic attack.\nDamage = (Power - MagicDefence) * Random[Magic, Magic + (Level + Magic) / 8]\nStatus Hit Rate = SpellAccuracy\n\nDamage Modifiers\n Caster : Multi-targeting, Mini and Elemental Boost\n Target : Shell and Elemental Affinity\nMiss on flying targets if the spell is Earth-elemental." },
	{ 10, L"Magic Heal", L"Basic heal (usable out of battles), damaging Zombie targets.\nHeal = Power * Random[Magic, Magic + (Level + Magic) / 8]\n\nHeal Modifiers : Multi-targeting, Concentrate, Petrify (miss) and Mini" },
	{ 11, L"Bad Status", L"Add status if the target is not immune.\nHit Rate = Accuracy + Magic / 4 + Level - TargetLevel\n\nHit Rate Modifiers : Multi-targeting and Shell\nUse magical evasion." },
	{ 12, L"Cure Status", L"Cure statuses (usable out of battles)." },
	{ 13, L"Life", L"Cure status and heal a player character (usable out of battles). On Zombie targets, the spell misses if the target is also KO and kills it instead else.\nHeal = (Spirit + Power) * MaxHP / 100\nHit Rate (Zombie) = Accuracy + Magic / 4 + Level - TargetLevel\n\nHeal Modifiers : Concentrate\nUse magical evasion." },
	{ 14, L"Death", L"Add status. On Zombie, the target is fully HP healed instead.\nHit Rate (Add Status) = Accuracy + Magic / 4 + Level - TargetLevel\n\nUse magical evasion.\nNever hit with the Easy Kill guard." },
	{ 15, L"Osmose", L"Magic attack stealing target's MP, but reverse the effect on Zombie.\nDamage MP = (Power - MagicDefence) * Random[Magic, Magic + (Level + Magic) / 8] / 4\n\nDamage MP Modifiers : Mini (Caster), Petrify (miss) and Shell" },
	{ 16, L"Drain", L"Magic attack stealing target's HP, but reverse the effect on Zombie.\nDamage = (Power - MagicDefence) * Random[Magic, Magic + (Level + Magic) / 8]\n\nDamage Modifiers : Mini (Caster), Petrify (miss) and Shell" },
	{ 17, L"Gravity", L"Magic attack depending on target's max HP.\nDamage = MaxHP * Power / 100\nHit Rate = Accuracy + Magic / 4 + Level - TargetLevel\n\nDamage Modifiers : Elemental Affinity and Boost\nHit Rate Modifiers : Multi-targeting, Shell and Easy Kill.\nUse magical evasion.\nMiss on flying targets if the spell is Earth-elemental." },
	{ 18, L"Random Magic", L"Magic attack with a wide range of damage that can also add status.\nExcept for a few spell slots, it never misses (see btl_calc::DecideMeteor).\nDamage = Power * Random[1, Level + Magic - 1]\nStatus Hit Rate = SpellAccuracy\n\nDamage Modifiers : Multi-targeting, Mini (Caster), Shell, Elemental Affinity and Boost\nMiss on flying targets if the spell is Earth-elemental." },
	{ 19, L"Physical Strike", L"Physical attack that can also add status.\nDamage = (Attaque * Power / 10 - Defence) * Random[Strength, Strength + (Level + Strength) / 8]\nStatus Hit Rate = SpellAccuracy\n\nDamage Modifiers\n Caster : Berserk, Trance, Mini and Elemental Boost (Spell)\n Target : Defend, Protect, Sleep, Mini and Elemental Affinity (Weapon)" },
	{ 20, L"Magic Weapon", L"Magic attack using strength that can also add status.\nDamage = (Attaque * Power / 10 - MagicDefence) * Random[Strength, Strength + (Level + Strength) / 8]\nStatus Hit Rate = SpellAccuracy\n\nDamage Modifiers : Mini (half), Shell, Elemental Affinity and Boost (Spell)\nMiss on flying targets if the spell is Earth-elemental." },
	{ 21, L"Goblin Punch", L"Magic attack improved if target and caster are same level.\nBase Damage = (Power - MagicDefence) * Random[Magic, Magic + (Level + Magic) / 8]\nImproved Damage = (Power + Level) * Random[Magic, Magic + (Level + Magic) / 8]\n\nDamage Modifiers : Mini (half) and Shell" },
	{ 22, L"LV? Death", L"Bring HP to « Power » if target's level is a multiple of « Accuracy ».\nPass through any status immunity but miss if the target is under Petrify." },
	{ 23, L"LV? Attack", L"Magic attack if target's level is a multiple of « Accuracy ».\nDamage = (Power - MagicDefence) * Random[Magic, Magic + (Level + Magic) / 8]\n\nDamage Modifiers : Mini (Caster), Shell, Petrify (miss), Elemental Affinity and Boost" },
	{ 24, L"LV? Defless", L"Reduce both defence and magic defence if target's level is a multiple of « Accuracy » and not under Petrify.\nNew Defences = Random[0, Old Defences - 1]" },
	{ 25, L"Roulette", L"Bring HP to « Power » but fail if the target is under Easy Kill or Petrify.\nThe base Roulette spell slot randomizes the target but the others have a determinist target (see btl_cmd::CheckCommandCondition)." },
	{ 26, L"Pure Damage", L"Type free attack.\nDamage = Power * 100 + Accuracy" },
	{ 27, L"Matra Magic", L"Bring HP to « Power » but fail if the target is under Easy Kill or Petrify.\nHit Rate = Accuracy + Magic / 4 + Level - TargetLevel\n\nHit Rate Modifier : Shell\nUse magical evasion." },
	{ 28, L"Limit Glove", L"Pure damage if caster's HP are exactly 1 but miss otherwise.\nDamage = Power * 100 + Accuracy" },
	{ 29, L"Minus Strike", L"Type free attack.\nDamage = CasterMaxHP - CasterHP" },
	{ 30, L"White Wind", L"Heal depending on caster's max HP. Damage Zombie instead of healing them.\nHeal = CasterMaxHP / 3" },
	{ 31, L"Magic Hammer", L"Reduce target's MP.\nDamage MP = Random[0, TargetMP - 1]" },
	{ 32, L"Darkside", L"Physical attack costing 1/8 of caster's max HP and ignoring weapon's element.\nDamage = (Attack * Power / 10 - Defence) * Random[Strength, Strength + (Level + Strength) / 8]\n\nDamage Modifiers : Elemental Affinity and Boost (Spell)" },
	{ 33, L"Armor Break", L"Reduce target's defence by 50%.\nHit Rate = Accuracy + Magic / 4 + Level - TargetLevel\n\nHit Rate Modifier : Shell\nUse magical evasion." },
	{ 34, L"Power Break", L"Reduce target's strength by 25%.\nHit Rate = Accuracy + Magic / 4 + Level - TargetLevel\n\nHit Rate Modifier : Shell\nUse magical evasion." },
	{ 35, L"Mental Break", L"Reduce target's magic defence by 50%.\nHit Rate = Accuracy + Magic / 4 + Level - TargetLevel\n\nHit Rate Modifier : Shell\nUse magical evasion." },
	{ 36, L"Magic Break", L"Reduce target's magic by 25%.\nHit Rate = Accuracy + Magic / 4 + Level - TargetLevel\n\nHit Rate Modifier : Shell\nUse magical evasion." },
	{ 37, L"Chakra", L"Heal both HP and MP. The effect is doubled if the caster has Power Up.\nHeal = MaxHP * Power / 100\nMP Heal = MaxMP * Power / 100" },
	{ 38, L"Spare Change", L"Type free attack using gils.\nLost Gils = Level * Power.\nDamage = (LostGils * LostGils * Spirit) / (TotalGils * 10)\n\nDamage is spread between the targets." },
	{ 39, L"Lancer", L"Physical attack reducing both HP and MP.\nDamage = (Attack * Power / 10 - Defence) * Random[Strength, Strength + (Level + Strength) / 8]\nDamage MP = Damage / 16\n\nDamage Modifiers\n Caster : Berserk, Trance and Mini\n Target : Defend, Protect, Sleep and Mini" },
	{ 40, L"Dragon Breath", L"Type free attack on all the enemies depending on target's HP.\nDamage = MaxHP - HP" },
	{ 41, L"White Draw", L"Heal all the allies' MP depending on target's level.\nMP Heal = Random[0, TargetLevel * 2 - 1]" },
	{ 42, L"Throw", L"Physical attack using a weapon.\nDamage = (WeaponAttack * 2 - Defence) * Random[Strength, Strength + (Level + Strength) / 8]\n\nDamage Modifiers\n Caster : Healer, Berserk, Trance and Mini\n Target : Flying type, Defend, Protect, Sleep and Mini\nKill Frozen targets." },
	{ 43, L"Might", L"Increase target's stength.\nBonus = (100 / Power)%" },
	{ 44, L"Focus", L"Increase target's magic.\nBonus = (100 / Power)%" },
	{ 45, L"Sacrifice", L"Fully heal targets' HP and MP by consuming caster's HP and MP. Fail on Petrified targets." },
	{ 46, L"Soul Blade", L"Add status depending on caster's weapon.\nWork only if the equipped weapon is a thief sword (ID between 7 and 15)." },
	{ 47, L"Apply Effect", L"No effect by itself.\nUsed by the other spell effects to apply damage, status, etc..." },
	{ 48, L"Spear", L"Physical attack.\nDamage = 1.5 * (Attack - Defence) * Random[Strength, Strength + (Level + Strength) / 8]\n\nDamage Modifiers : Healer, High Jump (factor changed from 1.5 to 2), Mini (Caster - half), Defend, Protect, Sleep and Mini (Target)" },
	{ 49, L"Eidolon Phoenix", L"Magic Attack on target enemies and Life on target allies.\nDamage = Magic Attack formula using Phoenix's spell datas\nHeal = Life formula using Rebirth Flame's spell datas" },
	{ 50, L"Six Dragons", L"Randomly change target's HP and/or MP but fail if the target is under Petrify.\nRestore both HP and MP : 10%\nRestore HP : 20%\nRestore MP : 20%\nReduce HP to 1 : 15%\nReduce MP to 1 : 15%\nReduce both HP and MP to 1 : 20%" },
	{ 51, L"Curse", L"Add an elemental weakness.\nThe base Curse spell slots randomize the element but the others have a determinist element (see btl_cmd::CheckCommandCondition)." },
	{ 52, L"Angel's Snack", L"Use an item specified by « Power » on each target." },
	{ 53, L"Lucky Seven", L"Type free attack improved if the last figure of caster's HP is 7.\nBase Damage = 1\nImproved Damage = Random{7, 77, 777, 7777}" },
	{ 54, L"What's That!?", L"Place the target enemies in a back attack state but fail if the « Scripted Start » flag of the battle is on.\nAlso put the target allies back to their usual row position." },
	{ 55, L"Change", L"Toggle between front row and back row." },
	{ 56, L"Flee", L"Escape from battle. Always miss during an enemy attack.\nSuccess Rate Per Second = 200 * TeamMeanLevel / EnemiesMeanLevel / 16" },
	{ 57, L"Flee Skill", L"Escape from battle but lose 10% of enemies carried gils." },
	{ 58, L"Steal", L"Try to steal an item from the target ennemies." },
	{ 59, L"Scan", L"Display the target's statistics but fail if it is under Easy Kill." },
	{ 60, L"Detect", L"Display target's owned items." },
	{ 61, L"Charge!", L"Make low HP allies (under 15% of their max HP) attack a random target. Those attacks are considered as counters and can't trigger another counter." },
	{ 62, L"Item : Soft", L"Cure Status (usable out of battles). Kill the target instead if it has the Stone type and is not under Petrify." },
	{ 63, L"Sword Magic", L"Perform a basic attack with improved damage and custom element.\nDamage = (Attack + Power - Defence) * Random[Strength, Strength + (Level + Strength) / 8]\n\nDamage Modifiers : Elemental Affinity and Boost (Spell)\nMiss on flying targets if the spell is Earth-elemental." },
	{ 64, L"Special", L"Used by enemies for various purposes.\nDoesn't do anything by itself." },
	{ 65, L"Eat", L"Eat the target if his HP are low enough but fail if it is under Easy Kill, Petrify or is Human-type.\nThreshold = MaxHP / Power" },
	{ 66, L"Frog Drop", L"Type free attack depending on frogs catched.\nDamage = Level * NbFrogs" },
	{ 67, L"Thievery", L"Type free attack depending on items stolen.\nDamage = Speed * NbSteals / 2" },
	{ 68, L"Dragon's Crest", L"Type free attack depending on dragons killed.\nDamage = NbDragons * NbDragons" },
	{ 69, L"Item : Heal", L"Item heal improved in battle (usable out of battles). Reverse the effect on Zombie.\nHeal = ItemPower * 10\nImproved Heal = ItemPower* 15\n\nHeal Modifier : Chemist" },
	{ 70, L"Item : MP Heal", L"Item MP heal improved in battle (usable out of battles). Reverse the effect on Zombie.\nMP Heal = ItemPower * 10\nImproved Heal = ItemPower * 15\n\nHeal Modifier : Chemist" },
	{ 71, L"Item : Full Heal", L"Set target's HP and MP at max (usable out of battles). Reverse the effect on Zombie." },
	{ 72, L"Item : Revive", L"Cure status and heal a player character (usable out of battles) but fail is the target is under Petrify. On Zombie targets, it misses if the target is also KO and set its HP to Random[0, 9] instead else.\nHeal = Random[1, 10]" },
	{ 73, L"Item : Cure Status", L"Cure Statuses using the item's status list (usable out of battles)." },
	{ 74, L"Item : Ore Heal", L"Heal depending on amount of the corresponding item in the player's inventory.\nHeal = NbItem * Power" },
	{ 75, L"Item : Pepper Damage", L"Type free attack depending on amount of the corresponding item in the player's inventory.\nDamage = NbItem * Power" },
	{ 76, L"Item : Tent", L"Heal 50% of target's max HP and MP. Also has 50% chances to add statuses using the item's status list." },
	{ 77, L"Item : Dark Matter", L"Type free attack dealing max damage but fail if the target is under Petrify.\nDamage = 9999" },
	{ 78, L"Unused 78", L"No effect." },
	{ 79, L"Unused 79", L"No effect." },
	{ 80, L"Unused 80", L"No effect." },
	{ 81, L"Unused 81", L"No effect." },
	{ 82, L"Unused 82", L"No effect." },
	{ 83, L"Trance Spear", L"Physical attack.\nDamage = 1.5 * (Attack - Defence) * Random[0, Random[Strength, Strength + (Level + Strength) / 8]]\n\nDamage Modifiers : High Jump (factor changed from 1.5 to 2), Mini (Caster - half), Defend, Protect, Sleep and Mini (Target)\nDamage is spread between the targets" },
	{ 84, L"Jewel", L"Add an ore to the inventory.\nSuccess Rate = Accuracy + Magic / 4 + Level - TargetLevel\n\nSuccess Rate Modifier : Shell\nUse magical evasion." },
	{ 85, L"Eidolon Common", L"Magic attack possibly weakened (unless the supporting ability Boost is on).\nDamage = (Power - MagicDefence) * Random[Magic, Magic + (Level + Magic) / 8]\nWeakened Damage = Damage * 2 / 3\n\nDamage Modifiers : Mini (Caster - half), Shell, Elemental Affinity and Boost\nFor several spell slots, the amount of jewels or the caster's level increase the Power.\nMiss on flying targets if the spell is Earth-elemental." },
	{ 86, L"Eidolon Atomos", L"Magic attack depending on target's max HP, possibly weakened (unless the supporting ability Boost is on), but fail if the target is under Easy Kill.\nDamage = HPMax * Power / 100\nWeakened Damage = Damage * 2 / 3\n\nDamage Modifiers : Amethyst amount, Elemental Affinity and Boost\nMiss on flying targets if the spell is Earth-elemental." },
	{ 87, L"Eidolon Odin", L"Add status but fail if the target is under Easy Kill. If the caster's Odin Sword is on, it also deals magic damage possibly weakened.\nHit Rate = Accuracy + Magic / 4 + Level - TargetLevel + OreAmount / 2\nDamage = (Power + 100 - OreAmount - MagicDefence) * Random[Magic, Magic + (Level + Magic) / 8]\nWeakened Damage = Damage * 2 / 3\n\nUse magical evasion." },
	{ 88, L"Self-Destruct", L"Type free attack sacrifying the caster.\nDamage = CasterHP" },
	{ 89, L"HP Switching", L"Switch caster's and target's current HP but fail if the target is under Easy Kill or Petrify." },
	{ 90, L"Defless", L"Divide target's defence and magic defence by 2." },
	{ 91, L"Cannon", L"Magic attack depending on target's current HP.\nDamage = Power * HP / 100\nHit Rate = Accuracy + Magic / 4 + Level - TargetLevel\n\nDamage Modifiers : Elemental Affinity and Boost\nHit Rate Modifiers : Multi-targeting and Shell\nMiss on flying targets if the spell is Earth-elemental." },
	{ 92, L"Add Item", L"Give an item specified by « Power » to the player." },
	{ 93, L"Maelstrom", L"Bring HP to a random number between 1 and 10 and add status but fail if the target is under Easy Kill or Petrify." },
	{ 94, L"Absorb Magic", L"Divide by 2 the target's magic and multiply by 2 the caster's.\nCan break the magic limit up to 255." },
	{ 95, L"Absorb Strength", L"Divide by 2 the target's strength and multiply by 2 the caster's.\nCan break the strength limit up to 255." },
	{ 96, L"Trance", L"Turn the target on trance." },
	{ 97, L"Entice", L"Add status but fail on girls." },
	{ 98, L"Terran Strike", L"Physical attack that misses on terran people.\nDamage = (Power - Defence) * Random[Strength, Strength + (Level + Strength) / 4]" },
	{ 99, L"Flare Star", L"Type free attack depending on target's level.\nDamage = Power * TargetLevel\nHit Rate = Accuracy + Magic / 4 + Level - TargetLevel\n\nHit Rate Modifiers : Multi-targeting and Shell\nUse magical evasion." },
	{ 100, L"Enemy Accurate Attack", L"Physical attack used by enemies that never misses and can also add status.\nDamage = (Power - Defence) * Random[Strength, Strength + (Level + Strength) / 4]\n\nDamage Modifiers\n Caster : Berserk, Trance, Mini, Back Row and Elemental Boost\n Target : Defend, Protect, Sleep, Mini, Back Attack, Back Row, Gamble Defence and Elemental Affinity\nKill Frozen targets." },
	{ 101, L"Inventory Steal", L"Remove an item from the player's inventory specified by « Accuracy ».\nHit Rate = 100\n\nUse physical evasion." },
	{ 102, L"Inventory Mug", L"Physical attack.\nAlso Remove an item from the player's inventory specified by « Accuracy ».\nDamage = (Power - Defence) * Random[Strength, Strength + (Level + Strength) / 4]\n\nDamage Modifiers : Berserk, Trance, Mini (Caster and Target), Defend, Protect, Sleep, Back Attack, Back Row, Gamble Defence" },
	{ 103, L"Good Status", L"Add status with a 100% hit rate if the target is not immune." },
	{ 104, L"Grudge", L"Type free attack depending on Tonberry killed.\nDamage = 4 ^ NbTonberry" },
	{ 105, L"Grand Cross", L"Add random statuses among the following, but fail if the target is under Petrify :\nPetrify, Silence, Darkness, Trouble, Zombie, Instant Death, Confuse, Berserk, Stop, Poison, Sleep, Heat, Freeze, Doom, Mini and HP reduce to 1-10.\nHit Rate (each status) = 1 / 8" },
	{ 106, L"Banish", L"Remove target from battle." },
	{ 107, L"Beat Back", L"Physical attack that can change the target's row (after damage) and can also add status.\nIf the target is a player character, he is moved to back row. Else, the target moves forward, preventing further front/back row modifiers.\nDamage = (Power - Defence) * Random[Strength, Strength + (Level + Strength) / 4]\n\nDamage Modifiers\n Caster : Berserk, Trance, Mini, Back Row and Elemental Boost\n Target : Defend, Protect, Sleep, Mini, Back Attack, Back Row, Gamble Defence and Elemental Affinity" },
	{ 108, L"Iai Strike", L"Add status but fail if the target is under Easy Kill.\nHit Rate = Accuracy + Magic / 4 + Level - TargetLevel\n\nHit Rate Modifiers : Multi-targeting and Shell\nUse magical evasion." },
	{ 109, L"Mini", L"Add status. Has a 100% hit rate if target is under Mini.\nHit Rate = Accuracy + Magic / 4 + Level - TargetLevel\n\nHit Rate Modifiers : Multi-targeting and Shell\nUse magical evasion." },
	{ 110, L"Unused 110", L"No effect." },
	{ 111, L"Unused 111", L"No effect." },
	{ 112, L"Unused 112", L"No effect." },
	{ 113, L"Unused 113", L"No effect." },
	{ 114, L"Unused 114", L"No effect." },
	{ 115, L"Unused 115", L"No effect." },
	{ 116, L"Unused 116", L"No effect." },
	{ 117, L"Unused 117", L"No effect." },
	{ 118, L"Unused 118", L"No effect." },
	{ 119, L"Unused 119", L"No effect." },
	{ 120, L"Unused 120", L"No effect." },
	{ 121, L"Unused 121", L"No effect." },
	{ 122, L"Unused 122", L"No effect." },
	{ 123, L"Unused 123", L"No effect." },
	{ 124, L"Unused 124", L"No effect." },
	{ 125, L"Unused 125", L"No effect." },
	{ 126, L"Unused 126", L"No effect." },
	{ 127, L"Unused 127", L"No effect." }
};

#define HADES_STRING_STATUS_NONE	L"No Status"
static SortedChoiceItem HADES_STRING_STATUS_PACK[] = {
	{ 0xFFFFFFFF, L"Everything" },
	{ 0xBFFF3C7F, L"All Statuses" },
	{ 0x24EC2000, L"All Good" },
	{ 0x9B13147F, L"All Bad" },
	{ 0x93030418, L"Esuna" },
	{ 0x10110410, L"Bad Breath" },
	{ 0x00C00000, L"Mighty Guard" },
	{ 0x00042000, L"Aura" },
};

static wxString HADES_STRING_STATUS[] = {
	L"Petrify",
	L"Venom",
	L"Virus",
	L"Silence",
	L"Darkness",
	L"Trouble",
	L"Zombie",
	L"Easy Kill",
	L"Death",
	L"Low HP",
	L"Confuse",
	L"Berserk",
	L"Stop",
	L"Auto-Life",
	L"Trance",
	L"Defend",
	L"Poison",
	L"Sleep",
	L"Regen",
	L"Haste",
	L"Slow",
	L"Float",
	L"Shell",
	L"Protect",
	L"Heat",
	L"Freeze",
	L"Vanish",
	L"Doom",
	L"Mini",
	L"Reflect",
	L"Jump",
	L"Gradual Petrify"
};

#endif
