#ifndef _DATABASE_TEXT_H
#define _DATABASE_TEXT_H

#include "Database_Common.h"

struct SortedChoiceItemTextOpcode {
	unsigned int id;
	wstring label;
	wstring converted;
	wstring help;
	int length;
	int type;
	wstring* arg_help;
};

static SortedChoiceItem HADES_STRING_TEXT_BLOCK_NAME[] = {
	{ 0x0, L"Generic UI" },
	{ 0x1, L"Debug Room" },
	{ 0x2, L"Prima Vista" },
	{ 0x3, L"Alexandria Castle (1)" },
	{ 0x4, L"Evil Forest" },
	{ 0x7, L"Cleyra Trunk" },
	{ 0x8, L"Ice Cavern" },
	{ 0x12, L"Red Rose" },
	{ 0x16, L"Lindblum Castle (1)" },
	{ 0x17, L"Mist Gates" },
	{ 0x1E, L"Terra" },
	{ 0x1F, L"Mountain Path" },
	{ 0x20, L"Conde Petie" },
	{ 0x21, L"Alexandria (1)" },
	{ 0x25, L"Black Mage Village (1)" },
	{ 0x26, L"Mognet Central" },
	{ 0x28, L"Prima Vista (Ruin)" },
	{ 0x2A, L"Quan's Dwelling" },
	{ 0x2C, L"Cleyra" },
	{ 0x2F, L"Dali" },
	{ 0x32, L"Dali Underground" },
	{ 0x33, L"Gizamaluke Grotto" },
	{ 0x34, L"Bran Bal" },
	{ 0x35, L"Observatory Mountain" },
	{ 0x3F, L"Cargo Ship" },
	{ 0x44, L"World Map" },
	{ 0x46, L"Treno (1)" },
	{ 0x47, L"Qu's Marsh" },
	{ 0x4A, L"South Gate" },
	{ 0x4D, L"Burmecia" },
	{ 0x58, L"Alexandria Castle (3)" },
	{ 0x59, L"Alexander" },
	{ 0x5A, L"Alexandria (2)" },
	{ 0x5B, L"Alexandria (Night)" },
	{ 0x79, L"Shrines" },
	{ 0x7C, L"Oeilvert" },
	{ 0x86, L"Pinnacle Rocks" },
	{ 0xA6, L"Daguerreo" },
	{ 0xBA, L"Hilda Garde III" },
	{ 0xBB, L"Ending" },
	{ 0xBD, L"Invincible" },
	{ 0xDF, L"Treno & Supersoft" },
	{ 0x114, L"Lindblum (1)" },
	{ 0x121, L"Alexandria Castle (2)" },
	{ 0x122, L"Cleyra (Stormless)" },
	{ 0x158, L"Pandemonium" },
	{ 0x166, L"Madain Sari (1)" },
	{ 0x167, L"Gargan Roo" },
	{ 0x168, L"Madain Sari (2)" },
	{ 0x169, L"Fossil Roo" },
	{ 0x1E4, L"Mount Gulug" },
	{ 0x1E5, L"Lindblum (Occupied)" },
	{ 0x20D, L"Lindblum Castle (Occupied)" },
	{ 0x253, L"Lindblum (2)" },
	{ 0x2B6, L"Memoria" },
	{ 0x2E2, L"Iifa Tree Roots" },
	{ 0x2E3, L"Ipsen Castle" },
	{ 0x2E4, L"Desert Palace" },
	{ 0x2E5, L"Treno (2)" },
	{ 0x2F2, L"Alexandria Castle (Ruin)" },
	{ 0x38C, L"Esto Gaza" },
	{ 0x3AF, L"Lindblum Castle (2)" },
	{ 0x3B0, L"Iifa Tree" },
	{ 0x3B1, L"Chocobo Places" },
	{ 0x3B2, L"Alexandria (Ruin)" },
	{ 0x431, L"Black Mage Village (2)" },
	{ 0x1000, L"Charmap" }
};

// Should always be sorted by id
#define TEXT_OPCODE_FORMAT_TYPE 0x80 // 0x80 and next ones
static SortedChoiceItemTextOpcode HADES_STRING_TEXT_OPCODE[] = {
	{ 0x00, L"[0x00]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x01, L"[TIMED_END]", L"", L"Terminate the dialog after few seconds\nOnly use at the end of the string", 1, 1, new wstring[1]{ L"Time to wait" } },
	{ 0x02, L"[SLOW]", L"", L"Slow down the appearing rate\n1 is the slowest", 1, 1, new wstring[1]{ L"Slow ratio" } },
	{ 0x03, L"FORMAT:03", L"", L"Unknown Format Opcode", 3, TEXT_OPCODE_FORMAT_TYPE+1, new wstring[3]{ L"Unknown", L"Unknown", L"Unknown" } },
	{ 0x04, L"[TOKENIZE]", L"", L"Create tokens from the string to be used in other strings\nMust be the only opcode of the string", -1, 4, new wstring[2]{ L"Token amount", L"Tokens" } },
	{ 0x05, L"[0x05]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x06, L"[VAR_TOKEN]", L"Token", L"Replaced by a tokenized string from another string", 2, 2, new wstring[2]{ L"Text ID", L"Script ID" } },
	{ 0x07, L"FORMAT:07", L"", L"Unknown Format Opcode", 2, TEXT_OPCODE_FORMAT_TYPE+2, new wstring[2]{ L"Unknown", L"Unknown" } },
	{ 0x08, L"[INIT_MULTICHOICE]", L"", L"Each line becomes a choice inside the dialog", 0, 0, NULL },
	{ 0x09, L"[AUTO_END]", L"", L"Terminate the dialog after few seconds\nOnly use at the end of the string", 0, 0, NULL },
	{ 0x0A, L"[0x0A]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x0B, L"FORMAT:0B", L"", L"Unknown Format Opcode", 0, TEXT_OPCODE_FORMAT_TYPE, NULL },
	{ 0x0C, L"[DISPLAY_INSTANT]", L"", L"Instantatly display the whole string", 0, 0, NULL },
	{ 0x0D, L"FORMAT:0D", L"", L"Unknown Format Opcode", -1, TEXT_OPCODE_FORMAT_TYPE+4, NULL },
	{ 0x0E, L"[VAR_ITEM]", L"Item", L"Replaced by some item's name set by the game script", 1, 1, new wstring[1]{ L"Script ID" } },
	{ 0x0F, L"[PROGRESSION]", L"", L"Tell the dialog's step progression to the game script", 1, 1, new wstring[1]{ L"Step" } },
	{ 0x10, L"[ZIDANE]", L"Zidane", L"Replaced by Zidane's name", 0, 0, NULL },
	{ 0x11, L"[VIVI]", L"Vivi", L"Replaced by Vivi's name", 0, 0, NULL },
	{ 0x12, L"[DAGGER]", L"Dagger", L"Replaced by Dagger's name", 0, 0, NULL },
	{ 0x13, L"[STEINER]", L"Steiner", L"Replaced by Steiner's name", 0, 0, NULL },
	{ 0x14, L"[FREYA]", L"Freya", L"Replaced by Freya's name", 0, 0, NULL },
	{ 0x15, L"[QUINA]", L"Quina", L"Replaced by Quina's name", 0, 0, NULL },
	{ 0x16, L"[EIKO]", L"Eiko", L"Replaced by Eiko's name", 0, 0, NULL },
	{ 0x17, L"[AMARANT]", L"Amarant", L"Replaced by Amarant's name", 0, 0, NULL },
	{ 0x18, L"[PARTY_1]", L"Cinna", L"Replaced by the name of the external character", 0, 0, NULL },
	{ 0x19, L"[PARTY_2]", L"Marcus", L"Replaced by the name of the external character (2)", 0, 0, NULL },
	{ 0x1A, L"[PARTY_3]", L"Blank", L"Replaced by the name of the external character (3)", 0, 0, NULL },
	{ 0x1B, L"[PARTY_4]", L"Beatrix", L"Replaced by the name of the external character (4)", 0, 0, NULL },
	{ 0x1C, L"[0x1C]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x1D, L"[0x1D]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x1E, L"[0x1E]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x1F, L"[0x1F]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x20, L"[WHITE]", L"", L"Change the color to white", 0, 0, NULL },
	{ 0x21, L"[WHITE_NO_SHADOW]", L"", L"Change the color to white with no shadow", 0, 0, NULL },
	{ 0x22, L"[GREY]", L"", L"Change the color to grey", 0, 0, NULL },
	{ 0x23, L"[RED]", L"", L"Change the color to red", 0, 0, NULL },
	{ 0x24, L"[YELLOW]", L"", L"Change the color to yellow", 0, 0, NULL },
	{ 0x25, L"[CYAN]", L"", L"Change the color to cyan", 0, 0, NULL },
	{ 0x26, L"[MAUVE]", L"", L"Change the color to mauve", 0, 0, NULL },
	{ 0x27, L"[GREEN]", L"", L"Change the color to green", 0, 0, NULL },
	{ 0x28, L"[BLACK_HELP]", L"", L"Change the color to black\nHelp dialogs only", 0, 0, NULL },
	{ 0x29, L"[RED_HELP]", L"", L"Change the color to red\nHelp dialogs only", 0, 0, NULL },
	{ 0x2A, L"[0x2A]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x2B, L"[0x2B]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x2C, L"[0x2C]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x2D, L"[0x2D]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x2E, L"[0x2E]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x2F, L"[BUTTON_PAD]", L"Pad", L"Replaced by a directional cross image", 0, 0, NULL },
	{ 0x30, L"[BUTTON_CIRCLE]", L"Circle", L"Replaced by a Circle button", 0, 0, NULL },
	{ 0x31, L"[BUTTON_CROSS]", L"Cross", L"Replaced by a Cross button", 0, 0, NULL },
	{ 0x32, L"[BUTTON_TRIANGLE]", L"Triangle", L"Replaced by a Triangle button", 0, 0, NULL },
	{ 0x33, L"[BUTTON_SQUARE]", L"Square", L"Replaced by a Square button", 0, 0, NULL },
	{ 0x34, L"[BUTTON_L1]", L"L1", L"Replaced by a L1 button", 0, 0, NULL },
	{ 0x35, L"[BUTTON_R1]", L"R1", L"Replaced by a R1 button", 0, 0, NULL },
	{ 0x36, L"[BUTTON_L2]", L"L2", L"Replaced by a L2 button", 0, 0, NULL },
	{ 0x37, L"[BUTTON_R2]", L"R2", L"Replaced by a R2 button", 0, 0, NULL },
	{ 0x38, L"[BUTTON_START]", L"Start", L"Replaced by a Start button", 0, 0, NULL },
	{ 0x39, L"[BUTTON_SELECT]", L"Select", L"Replaced by a Select button", 0, 0, NULL },
	{ 0x3A, L"[BUTTON_UP]", L"Up", L"Replaced by a Up button", 0, 0, NULL },
	{ 0x3B, L"[BUTTON_DOWN]", L"Down", L"Replaced by a Down button", 0, 0, NULL },
	{ 0x3C, L"[BUTTON_LEFT]", L"Left", L"Replaced by a Left button", 0, 0, NULL },
	{ 0x3D, L"[BUTTON_RIGHT]", L"Right", L"Replaced by a Right button", 0, 0, NULL },
	{ 0x3E, L"[BUTTON_L2]", L"L2", L"Replaced by a L2 button", 0, 0, NULL },
	{ 0x3F, L"[BUTTON_R2]", L"R2", L"Replaced by a R2 button", 0, 0, NULL },
	{ 0x40, L"[VAR_NUM]", L"0", L"Replaced by some number set by the game script", 1, 1, new wstring[1]{ L"Script ID" } },
	{ 0x41, L"[PAUSE]", L"", L"Stop the appearance for few seconds", 1, 1, new wstring[1]{ L"Frame to wait" } },
	{ 0x42, L"[RESUME_SPEED]", L"", L"Resume the appearing rate", 0, 0, NULL },
	{ 0x43, L"[CARET_POSITION_REL]", L"", L"Change the caret position in the line", 1, 1, new wstring[1]{ L"Relative position" } },
	{ 0x44, L"[CARET_POSITION_ABS]", L"", L"Change the caret position in the line", 1, 1, new wstring[1]{ L"Absolute position" } },
	{ 0x45, L"[0x45]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x46, L"[0x46]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x47, L"[0x47]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x48, L"[0x48]", L"", L"Unknown Opcode", -1, 5, new wstring[1]{ L"Amount" } },
	{ 0x49, L"[0x49]", L"", L"Unknown Opcode", 1, 1, new wstring[1]{ L"Unknown" } },
	{ 0x4A, L"[0x4A]", L"", L"Unknown Opcode", 1, 1, new wstring[1]{ L"Unknown" } },
	{ 0x4B, L"[IMAGE]", L"", L"Replaced by an image", 1, 1, new wstring[1]{ L"Image ID" } },
	{ 0x4C, L"[ICON_ITEM]", L"", L"Replaced by the icon of an item", 1, 1, new wstring[1]{ L"Item ID" } },
	{ 0x4D, L"[RAM_STATUS]", L"", L"Replaced by a status icon - Use RAM setup", 1, 1, new wstring[1]{ L"Unknown" } },
	{ 0x4E, L"[RAM_EQUIPMENT]", L"", L"Replaced by an equipment icon - Use RAM setup", 1, 1, new wstring[1]{ L"Unknown" } },
	{ 0x4F, L"FORMAT:4F", L"", L"Unknown Format Opcode", 2, TEXT_OPCODE_FORMAT_TYPE+2, new wstring[2]{ L"Unknown", L"Unknown" } },
	{ 0x50, L"FORMAT:50", L"", L"Unknown Format Opcode", 0, TEXT_OPCODE_FORMAT_TYPE, NULL },
	{ 0x51, L"FORMAT:51", L"", L"Unknown Format Opcode", 0, TEXT_OPCODE_FORMAT_TYPE, NULL },
	{ 0x52, L"FORMAT:52", L"", L"Unknown Format Opcode", 0, TEXT_OPCODE_FORMAT_TYPE, NULL },
	{ 0x53, L"FORMAT:53", L"", L"Unknown Format Opcode", 0, TEXT_OPCODE_FORMAT_TYPE, NULL },
	{ 0x54, L"FORMAT:54", L"", L"Unknown Format Opcode", 0, TEXT_OPCODE_FORMAT_TYPE, NULL },
	{ 0x55, L"FORMAT:55", L"", L"Unknown Format Opcode", 0, TEXT_OPCODE_FORMAT_TYPE, NULL },
	{ 0x56, L"[0x56]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x57, L"[0x57]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x58, L"FORMAT:Switch Up/Down", L"", L"Display the bubble over or under the talker", 0, TEXT_OPCODE_FORMAT_TYPE, NULL },
	{ 0x59, L"FORMAT:59", L"", L"Unknown Format Opcode", 0, TEXT_OPCODE_FORMAT_TYPE, NULL },
	{ 0x5A, L"FORMAT:5A", L"", L"Unknown Format Opcode", 0, TEXT_OPCODE_FORMAT_TYPE, NULL },
	{ 0x5B, L"FORMAT:5B", L"", L"Unknown Format Opcode", 0, TEXT_OPCODE_FORMAT_TYPE, NULL },
	{ 0x5C, L"FORMAT:5C", L"", L"Unknown Format Opcode", 0, TEXT_OPCODE_FORMAT_TYPE, NULL },
	{ 0x5D, L"[0x5D]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x5E, L"[0x5E]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x5F, L"FORMAT:Talker Gap", L"", L"Add a gap from the talker's position", 6, TEXT_OPCODE_FORMAT_TYPE+3, NULL },
	{ 0x60, L"[BUTTONEX_CIRCLE]", L"Circle", L"Replaced by the confirm button", 0, 0, NULL },
	{ 0x61, L"[BUTTONEX_CROSS]", L"Cross", L"Replaced by the cancel button", 0, 0, NULL },
	{ 0x62, L"[BUTTONEX_TRIANGLE]", L"Triangle", L"Replaced by the menu button", 0, 0, NULL },
	{ 0x63, L"[BUTTONEX_SQUARE]", L"Square", L"Replaced by the moogle button", 0, 0, NULL },
	{ 0x64, L"[BUTTONEX_L1]", L"L1", L"Replaced by the button associated to L1", 0, 0, NULL },
	{ 0x65, L"[BUTTONEX_R1]", L"R1", L"Replaced by the button associated to R1", 0, 0, NULL },
	{ 0x66, L"[BUTTONEX_L2]", L"L2", L"Replaced by the button associated to L2", 0, 0, NULL },
	{ 0x67, L"[BUTTONEX_R2]", L"R2", L"Replaced by the button associated to R2", 0, 0, NULL },
	{ 0x68, L"[RAM_NUM]", L"0", L"Replaced by a number - Use RAM setup", 1, 1, new wstring[1]{ L"Unknown" } },
	{ 0x69, L"[RAM_TEXT]", L"Text", L"Replaced by some text - Use RAM setup", 1, 1, new wstring[1]{ L"Unknown" } },
	{ 0x6A, L"[0x6A]", L"", L"Unknown Opcode", 1, 1, new wstring[1]{ L"Unknown" } },
	{ 0x6B, L"[RAM_DATA]", L"", L"Replaced by a character's data value - Use RAM setup", 1, 1, new wstring[1]{ L"Unknown" } },
	{ 0x6C, L"[RAM_NUM_DESIGN]", L"0", L"Replaced by a designed number - Use RAM setup", 1, 1, new wstring[1]{ L"Unknown" } },
	{ 0x6D, L"[0x6D]", L"", L"Unknown Opcode", 1, 1, new wstring[1]{ L"Unknown" } },
	{ 0x6E, L"[0x6E]", L"", L"Unknown Opcode", 1, 1, new wstring[1]{ L"Unknown" } },
	{ 0x6F, L"[0x6F]", L"", L"Unknown Opcode", 1, 1, new wstring[1]{ L"Unknown" } },
	{ 0x70, L"[IMAGE_NEW]", L"!New", L"Possibly replaced by a 'New' indicator", 1, 1, new wstring[1]{ L"Script ID" } },
	{ 0x71, L"[INDENT]", L"", L"Same as CARET_POSITION_ABS(18)", 0, 0, NULL },
	{ 0x72, L"[0x72]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x73, L"[0x73]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x74, L"[0x74]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x75, L"[0x75]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x76, L"[0x76]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x77, L"[0x77]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x78, L"[0x78]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x79, L"[0x79]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x7A, L"[0x7A]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x7B, L"[0x7B]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x7C, L"[0x7C]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x7D, L"[0x7D]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x7E, L"[0x7E]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x7F, L"[0x7F]", L"", L"Unknown Opcode", 0, 0, NULL },
	{ 0x80, L"[0x80]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x81, L"[0x81]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x82, L"[0x82]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x83, L"[0x83]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x84, L"[0x84]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x85, L"[0x85]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x86, L"[0x86]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x87, L"[0x87]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x88, L"[0x88]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x89, L"[0x89]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x8A, L"[0x8A]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x8B, L"[0x8B]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x8C, L"[0x8C]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x8D, L"[0x8D]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x8E, L"[0x8E]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x8F, L"[0x8F]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x90, L"[0x90]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x91, L"[0x91]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x92, L"[0x92]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x93, L"[0x93]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x94, L"[0x94]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x95, L"[0x95]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x96, L"[0x96]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x97, L"[0x97]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x98, L"[0x98]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x99, L"[0x99]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x9A, L"[0x9A]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x9B, L"[0x9B]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x9C, L"[0x9C]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x9D, L"[0x9D]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x9E, L"[0x9E]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0x9F, L"[0x9F]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xA0, L"[0xA0]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xA1, L"[0xA1]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xA2, L"[0xA2]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xA3, L"[0xA3]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xA4, L"[0xA4]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xA5, L"[0xA5]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xA6, L"[0xA6]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xA7, L"[0xA7]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xA8, L"[0xA8]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xA9, L"[0xA9]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xAA, L"[0xAA]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xAB, L"[0xAB]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xAC, L"[0xAC]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xAD, L"[0xAD]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xAE, L"[0xAE]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xAF, L"[0xAF]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xB0, L"[0xB0]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xB1, L"[0xB1]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xB2, L"[0xB2]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xB3, L"[0xB3]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xB4, L"[0xB4]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xB5, L"[0xB5]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xB6, L"[0xB6]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xB7, L"[0xB7]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xB8, L"[0xB8]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xB9, L"[0xB9]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xBA, L"[0xBA]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xBB, L"[0xBB]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xBC, L"[0xBC]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xBD, L"[0xBD]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xBE, L"[0xBE]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xBF, L"[0xBF]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xC0, L"[0xC0]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xC1, L"[0xC1]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xC2, L"[0xC2]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xC3, L"[0xC3]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xC4, L"[0xC4]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xC5, L"[0xC5]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xC6, L"[0xC6]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xC7, L"[0xC7]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xC8, L"[0xC8]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xC9, L"[0xC9]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xCA, L"[0xCA]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xCB, L"[0xCB]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xCC, L"[0xCC]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xCD, L"[0xCD]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xCE, L"[0xCE]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xCF, L"[0xCF]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xD0, L"[0xD0]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xD1, L"[0xD1]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xD2, L"[0xD2]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xD3, L"[0xD3]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xD4, L"[0xD4]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xD5, L"[0xD5]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xD6, L"[0xD6]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xD7, L"[0xD7]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xD8, L"[0xD8]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xD9, L"[0xD9]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xDA, L"[0xDA]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xDB, L"[0xDB]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xDC, L"[0xDC]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xDD, L"[0xDD]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xDE, L"[0xDE]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xDF, L"[0xDF]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xE0, L"[0xE0]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xE1, L"[0xE1]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xE2, L"[0xE2]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xE3, L"[0xE3]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xE4, L"[0xE4]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xE5, L"[0xE5]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xE6, L"[0xE6]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xE7, L"[0xE7]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xE8, L"[0xE8]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xE9, L"[0xE9]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xEA, L"[0xEA]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xEB, L"[0xEB]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xEC, L"[0xEC]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xED, L"[0xED]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xEE, L"[0xEE]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xEF, L"[0xEF]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xF0, L"[0xF0]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xF1, L"[0xF1]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xF2, L"[0xF2]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xF3, L"[0xF3]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xF4, L"[0xF4]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xF5, L"[0xF5]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xF6, L"[0xF6]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xF7, L"[0xF7]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xF8, L"[0xF8]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xF9, L"[0xF9]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xFA, L"[0xFA]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xFB, L"[0xFB]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xFC, L"[0xFC]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xFD, L"[0xFD]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xFE, L"[0xFE]", L"", L"Unknown Opcode", 0, -1, NULL },
	{ 0xFF, L"[0xFF]", L"", L"Unknown Opcode", 0, -1, NULL }
};

#endif
